#!/usr/bin/env python3
"""Verify or regenerate exhibits/_catalog.yaml from exhibit folders.

Usage:
  python tools/catalog.py --check
  python tools/catalog.py --write
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXHIBITS = ROOT / "exhibits"
CATALOG = EXHIBITS / "_catalog.yaml"

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None


def load_yaml(path: Path) -> dict:
    if yaml is None:
        raise RuntimeError("PyYAML is required: pip install pyyaml")
    with path.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    if not isinstance(data, dict):
        raise ValueError(f"{path}: expected mapping")
    return data


def discover() -> list[dict]:
    entries: list[dict] = []
    for path in sorted(EXHIBITS.iterdir()):
        if not path.is_dir() or path.name.startswith("_"):
            continue
        exhibit_path = path / "exhibit.yaml"
        if not exhibit_path.is_file():
            continue
        data = load_yaml(exhibit_path)
        entries.append(
            {
                "id": data.get("id"),
                "slug": data.get("slug", path.name),
                "title": data.get("title"),
                "status": data.get("status"),
                "version": data.get("version"),
                "path": f"exhibits/{path.name}",
                "tags": data.get("tags") or [],
            }
        )
    return entries


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true", help="Exit non-zero if catalog drifts")
    group.add_argument("--write", action="store_true", help="Regenerate _catalog.yaml")
    args = parser.parse_args()

    try:
        discovered = discover()
    except (OSError, RuntimeError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    generated = {"exhibits": discovered}

    if args.write:
        if yaml is None:
            print("PyYAML is required: pip install pyyaml", file=sys.stderr)
            return 2
        text = yaml.safe_dump(generated, sort_keys=False, allow_unicode=True)
        header = "# Generated by tools/catalog.py — prefer editing exhibit.yaml then --write\n"
        CATALOG.write_text(header + text, encoding="utf-8")
        print(f"Wrote {CATALOG.relative_to(ROOT)} ({len(discovered)} exhibits)")
        return 0

    # --check
    if not CATALOG.is_file():
        print("catalog missing", file=sys.stderr)
        return 1
    try:
        current = load_yaml(CATALOG)
    except (OSError, RuntimeError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    current_slugs = {e.get("slug") for e in (current.get("exhibits") or [])}
    discovered_slugs = {e["slug"] for e in discovered}
    missing = discovered_slugs - current_slugs
    extra = current_slugs - discovered_slugs
    if missing or extra:
        if missing:
            print(f"catalog missing: {sorted(missing)}", file=sys.stderr)
        if extra:
            print(f"catalog extra: {sorted(extra)}", file=sys.stderr)
        return 1

    print(f"OK: catalog matches {len(discovered)} exhibit(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
